spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
 
    
##PARA EL ACTUATOR    
management:
  endpoints:
    web:
      exposure:
        include: "*"       