server:
  port: 8888
spring: 
  cloud:
    config:
      server:
        git:   #dirección repositorio remoto
          uri: https://github.com/amartinsierra/configuracion_servicios
        default-label: main ##para que busque en esta branch de git